# Generated by Django 6.0.7 on 2026-08-05 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('well_type', models.CharField(choices=[('Oil', 'Oil'), ('Gas', 'Gas'), ('Water Injector', 'Water Injector'), ('Gas Injector', 'Gas Injector'), ('Exploration', 'Exploration')], max_length=30)),
                ('status', models.CharField(choices=[('Drilling', 'Drilling'), ('Producing', 'Producing'), ('Shut In', 'Shut In'), ('Workover', 'Workover'), ('Abandoned', 'Abandoned')], default='Producing', max_length=20)),
                ('spud_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('total_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wells', to='fields.field')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wells', to='companies.company')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
