# Generated by Django 6.0.7 on 2026-08-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='artificial_lift',
            field=models.CharField(blank=True, choices=[('Natural Flow', 'Natural Flow'), ('ESP', 'ESP'), ('Gas Lift', 'Gas Lift'), ('Rod Pump', 'Rod Pump'), ('PCP', 'PCP'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='casing_size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='first_production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='formation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='well',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='reservoir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='true_vertical_depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='True Vertical Depth (m)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='tubing_size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='total_depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Measured Depth (m)', max_digits=8, null=True),
        ),
    ]
