# Generated by Django 6.0.7 on 2026-08-05 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wells', '0002_well_artificial_lift_well_casing_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurement_date', models.DateField()),
                ('shift', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], default='Day', max_length=10)),
                ('operating_status', models.CharField(choices=[('Running', 'Running'), ('Shut In', 'Shut In'), ('Maintenance', 'Maintenance'), ('Startup', 'Startup'), ('Shutdown', 'Shutdown')], default='Running', max_length=20)),
                ('wellhead_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tubing_head_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('casing_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flowline_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wellhead_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('flowline_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('choke_size', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('esp_frequency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('motor_current', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('water_cut', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bsw', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('downtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('downtime_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to=settings.AUTH_USER_MODEL)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='wells.well')),
            ],
            options={
                'ordering': ['-measurement_date'],
                'constraints': [models.UniqueConstraint(fields=('well', 'measurement_date', 'shift'), name='unique_well_measurement')],
            },
        ),
    ]
