# Generated by Django 6.0.7 on 2026-08-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_job_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('PRODUCTION_ENGINEER', 'Production Engineer'), ('FIELD_OPERATOR', 'Field Operator'), ('MAINTENANCE_ENGINEER', 'Maintenance Engineer'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=30),
        ),
    ]
