import { useEffect, useMemo, useState } from "react";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import api from "../../services/api";

const EMPTY_REPORT = { summary: {}, test_history: [], pressure_history: [], production_history: [], well_performance: [], declining_wells: [] };

export default function WellTestReport() {
  const [fields, setFields] = useState([]);
  const [wells, setWells] = useState([]);
  const [report, setReport] = useState(EMPTY_REPORT);
  const [filters, setFilters] = useState({ field: "", well: "", date_from: "", date_to: "" });
  const [loading, setLoading] = useState(false);
  const [exporting, setExporting] = useState("");
  const [error, setError] = useState("");

  const loadFields = async () => { try { const response = await api.get("/fields/"); setFields(response.data?.results || response.data || []); } catch (err) { console.error("Failed to load fields:", err); setFields([]); } };
  const loadWells = async (field = "") => { try { const response = await api.get("/wells/", { params: field ? { field } : {} }); setWells(response.data?.results || response.data || []); } catch (err) { console.error("Failed to load wells:", err); setWells([]); } };
  const loadReport = async () => {
    try {
      setLoading(true); setError("");
      const response = await api.get("/reports/well-tests/", { params: filters });
      setReport({ ...EMPTY_REPORT, ...(response.data || {}), summary: response.data?.summary || {}, test_history: response.data?.test_history || [], pressure_history: response.data?.pressure_history || [], production_history: response.data?.production_history || [], well_performance: response.data?.well_performance || [], declining_wells: response.data?.declining_wells || [] });
    } catch (err) { console.error("Failed to load well test report:", err); setError("Failed to load well test report."); } finally { setLoading(false); }
  };
  const exportReport = async (path, filename, type) => {
    try {
      setExporting(filename);
      const response = await api.get(path, { params: filters, responseType: "blob" });
      const url = window.URL.createObjectURL(new Blob([response.data], { type }));
      const link = document.createElement("a"); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove(); window.URL.revokeObjectURL(url);
    } catch (err) { console.error(`Failed to export ${filename}:`, err); setError(`Failed to export ${filename}.`); } finally { setExporting(""); }
  };
  useEffect(() => { loadFields(); loadReport(); }, []);
  useEffect(() => { loadWells(filters.field); }, [filters.field]);
  const updateFilter = (name, value) => setFilters((previous) => ({ ...previous, [name]: value, ...(name === "field" ? { well: "" } : {}) }));
  const clearFilters = () => setFilters({ field: "", well: "", date_from: "", date_to: "" });
  const testHistory = useMemo(() => report.test_history || [], [report.test_history]);
  const pressureHistory = useMemo(() => report.pressure_history || [], [report.pressure_history]);
  const productionHistory = useMemo(() => report.production_history || [], [report.production_history]);
  const wellPerformance = useMemo(() => report.well_performance || [], [report.well_performance]);
  const number = (value) => Number(value || 0).toLocaleString(undefined, { maximumFractionDigits: 2 });
  const selectClass = "mt-1 w-full rounded-lg border px-3 py-2.5 font-normal outline-none focus:border-blue-500";

  const ChartCard = ({ title, data, lines }) => <div className="rounded-xl border bg-white p-6 shadow-sm"><h2 className="mb-5 text-lg font-semibold">{title}</h2><div className="h-[300px]">{data.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ bottom: 20 }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" /><YAxis /><Tooltip /><Legend />{lines.map((line) => <Line key={line.key} type="monotone" dataKey={line.key} name={line.name} stroke={line.color} strokeWidth={3} dot={{ r: 3 }} connectNulls />)}</LineChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-sm text-gray-500">No well test data available.</div>}</div></div>;
  const cards = [["Total Tests", report.summary?.total_tests, ""], ["Average Oil Rate", report.summary?.average_oil_rate, "BOPD"], ["Average Gas Rate", report.summary?.average_gas_rate, "MSCFD"], ["Average Water Rate", report.summary?.average_water_rate, "BWPD"], ["Average WHP", report.summary?.average_wellhead_pressure, "psi"], ["Average BHP", report.summary?.average_bottomhole_pressure, "psi"], ["Average Water Cut", report.summary?.average_water_cut, "%"], ["Average GOR", report.summary?.average_gor, "scf/STB"]];

  return <div className="min-h-screen bg-gray-50 p-6">
    <div className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h1 className="text-2xl font-bold text-gray-900">Well Test Report</h1><p className="mt-1 text-sm text-gray-500">Analyze test rates, pressure, and well performance.</p></div><div className="flex flex-wrap gap-3"><button onClick={loadReport} disabled={loading} className="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50">{loading ? "Loading..." : "Generate Report"}</button><button disabled={!!exporting} onClick={() => exportReport("/reports/well-tests/export/pdf/", "well_test_report.pdf", "application/pdf")} className="rounded-lg bg-red-600 px-5 py-2.5 text-sm font-medium text-white hover:bg-red-700 disabled:opacity-50">{exporting === "well_test_report.pdf" ? "Exporting..." : "Export PDF"}</button><button disabled={!!exporting} onClick={() => exportReport("/reports/well-tests/export/excel/", "well_test_report.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")} className="rounded-lg bg-green-600 px-5 py-2.5 text-sm font-medium text-white hover:bg-green-700 disabled:opacity-50">{exporting === "well_test_report.xlsx" ? "Exporting..." : "Export Excel"}</button></div></div>
    {error && <div className="mb-6 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <div className="mb-6 rounded-xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold text-gray-900">Filters</h2><p className="text-sm text-gray-500">Filter well test records.</p></div><button onClick={clearFilters} className="text-sm font-medium text-blue-600 hover:text-blue-800">Clear Filters</button></div><div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-medium text-gray-700">Field<select value={filters.field} onChange={(event) => updateFilter("field", event.target.value)} className={selectClass}><option value="">All Fields</option>{fields.map((field) => <option key={field.id} value={field.id}>{field.name} {field.code ? `(${field.code})` : ""}</option>)}</select></label><label className="text-sm font-medium text-gray-700">Well<select value={filters.well} onChange={(event) => updateFilter("well", event.target.value)} className={selectClass}><option value="">All Wells</option>{wells.map((well) => <option key={well.id} value={well.id}>{well.code} - {well.name}</option>)}</select></label><label className="text-sm font-medium text-gray-700">Date From<input type="date" value={filters.date_from} onChange={(event) => updateFilter("date_from", event.target.value)} className={selectClass} /></label><label className="text-sm font-medium text-gray-700">Date To<input type="date" value={filters.date_to} onChange={(event) => updateFilter("date_to", event.target.value)} className={selectClass} /></label></div></div>
    <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value, unit]) => <div key={label} className="rounded-xl border bg-white p-5 shadow-sm"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-2xl font-bold text-gray-900">{number(value)}</p>{unit && <p className="mt-1 text-xs text-gray-400">{unit}</p>}</div>)}</div>
    <div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><div className="xl:col-span-2"><ChartCard title="Test Production Rates" data={productionHistory} lines={[{ key: "oil_rate", name: "Oil (BOPD)", color: "#16a34a" }, { key: "gas_rate", name: "Gas (MSCFD)", color: "#2563eb" }, { key: "water_rate", name: "Water (BWPD)", color: "#0891b2" }]} /></div><div className="xl:col-span-2"><ChartCard title="Pressure Analysis" data={pressureHistory} lines={[{ key: "wellhead_pressure", name: "Wellhead Pressure", color: "#7c3aed" }, { key: "bottomhole_pressure", name: "Bottomhole Pressure", color: "#dc2626" }]} /></div><ChartCard title="Water Cut Trend" data={testHistory} lines={[{ key: "water_cut", name: "Water Cut (%)", color: "#0891b2" }]} /><ChartCard title="GOR Trend" data={testHistory} lines={[{ key: "gor", name: "GOR", color: "#f59e0b" }]} /><div className="xl:col-span-2"><ChartCard title="Choke Size Trend" data={testHistory} lines={[{ key: "choke_size", name: "Choke Size", color: "#7c3aed" }]} /></div></div>
    <div className="mt-6 rounded-xl border bg-white p-6 shadow-sm"><h2 className="mb-5 text-lg font-semibold">Well Test History</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50"><tr className="border-b text-left"><th className="p-4">Date</th><th className="p-4">Well</th><th className="p-4">Oil</th><th className="p-4">Gas</th><th className="p-4">Water</th><th className="p-4">WHP</th><th className="p-4">BHP</th><th className="p-4">Choke</th><th className="p-4">Water Cut</th><th className="p-4">GOR</th></tr></thead><tbody>{testHistory.map((item, index) => <tr key={`${item.well}-${item.date}-${index}`} className="border-b hover:bg-gray-50"><td className="p-4">{item.date || "-"}</td><td className="p-4 font-medium">{item.well || "-"}</td><td className="p-4">{number(item.oil_rate)}</td><td className="p-4">{number(item.gas_rate)}</td><td className="p-4">{number(item.water_rate)}</td><td className="p-4">{item.wellhead_pressure ?? "-"}</td><td className="p-4">{item.bottomhole_pressure ?? "-"}</td><td className="p-4">{item.choke_size ?? "-"}</td><td className="p-4">{item.water_cut ?? "-"}</td><td className="p-4">{item.gor ?? "-"}</td></tr>)}{!testHistory.length && <tr><td colSpan="10" className="p-10 text-center text-gray-500">No well test data available.</td></tr>}</tbody></table></div></div>
    <div className="mt-6 rounded-xl border bg-white p-6 shadow-sm"><h2 className="mb-5 text-lg font-semibold">Well Performance</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50"><tr className="border-b text-left"><th className="p-4">Well</th><th className="p-4">Name</th><th className="p-4">Average Oil</th><th className="p-4">Average Gas</th><th className="p-4">Average Water</th><th className="p-4">Tests</th></tr></thead><tbody>{wellPerformance.map((item) => <tr key={item.well} className="border-b hover:bg-gray-50"><td className="p-4 font-medium">{item.well || "-"}</td><td className="p-4">{item.name || "-"}</td><td className="p-4">{number(item.average_oil_rate)}</td><td className="p-4">{number(item.average_gas_rate)}</td><td className="p-4">{number(item.average_water_rate)}</td><td className="p-4">{item.test_count ?? 0}</td></tr>)}{!wellPerformance.length && <tr><td colSpan="6" className="p-10 text-center text-gray-500">No well test data available.</td></tr>}</tbody></table></div></div>
  </div>;
}
