# Generated by Django 6.0.7 on 2026-08-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-start_date', '-start_time']},
        ),
        migrations.AddField(
            model_name='maintenance',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
