# Generated by Django 6.0.7 on 2026-08-05 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('wells', '0002_well_artificial_lift_well_casing_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intervention_type', models.CharField(choices=[('Wireline', 'Wireline'), ('Slickline', 'Slickline'), ('Coiled Tubing', 'Coiled Tubing'), ('Acid Stimulation', 'Acid Stimulation'), ('Hydraulic Fracturing', 'Hydraulic Fracturing'), ('ESP Installation', 'ESP Installation'), ('ESP Replacement', 'ESP Replacement'), ('Tubing Replacement', 'Tubing Replacement'), ('Cementing', 'Cementing'), ('Perforation', 'Perforation'), ('Fishing', 'Fishing'), ('Well Kill', 'Well Kill'), ('Other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planned', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='companies.company')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_interventions', to=settings.AUTH_USER_MODEL)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='wells.well')),
            ],
            options={
                'ordering': ['-start_date', '-start_time'],
            },
        ),
    ]
