# Generated by Django 6.0.7 on 2026-08-05 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wells', '0002_well_artificial_lift_well_casing_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_date', models.DateField()),
                ('oil_rate', models.DecimalField(decimal_places=2, default=0, help_text='BOPD', max_digits=10)),
                ('gas_rate', models.DecimalField(decimal_places=2, default=0, help_text='MSCFD', max_digits=10)),
                ('water_rate', models.DecimalField(decimal_places=2, default=0, help_text='BWPD', max_digits=10)),
                ('wellhead_pressure', models.DecimalField(blank=True, decimal_places=2, help_text='psi', max_digits=10, null=True)),
                ('bottomhole_pressure', models.DecimalField(blank=True, decimal_places=2, help_text='psi', max_digits=10, null=True)),
                ('choke_size', models.DecimalField(blank=True, decimal_places=2, help_text='1/64 inch', max_digits=5, null=True)),
                ('water_cut', models.DecimalField(blank=True, decimal_places=2, help_text='%', max_digits=5, null=True)),
                ('gor', models.DecimalField(blank=True, decimal_places=2, help_text='scf/STB', max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_tests', to='wells.well')),
            ],
            options={
                'ordering': ['-test_date'],
                'unique_together': {('well', 'test_date')},
            },
        ),
    ]
