# Generated by Django 6.0.7 on 2026-08-05 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wells', '0002_well_artificial_lift_well_casing_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_date', models.DateField()),
                ('oil_production', models.DecimalField(decimal_places=2, default=0, help_text='Barrels of Oil Per Day (BOPD)', max_digits=12)),
                ('gas_production', models.DecimalField(decimal_places=2, default=0, help_text='MSCFD', max_digits=12)),
                ('water_production', models.DecimalField(decimal_places=2, default=0, help_text='Barrels of Water Per Day (BWPD)', max_digits=12)),
                ('operating_hours', models.DecimalField(decimal_places=2, default=24.0, max_digits=5)),
                ('downtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='wells.well')),
            ],
            options={
                'ordering': ['-production_date'],
                'unique_together': {('well', 'production_date')},
            },
        ),
    ]
